//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mesa.HUM.UI.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mesa.HUM.UI.Desktop.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product can manage challenges for your team. Existing challenges can be accepted or denied, and new challenges can be created..
        /// </summary>
        public static string ChppScope_ManageChallenges_Description {
            get {
                return ResourceManager.GetString("ChppScope_ManageChallenges_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage challenges.
        /// </summary>
        public static string ChppScope_ManageChallenges_Title {
            get {
                return ResourceManager.GetString("ChppScope_ManageChallenges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product can manage your youth players. At the moment this only includes unlocking skills..
        /// </summary>
        public static string ChppScope_ManageYouthPlayers_Description {
            get {
                return ResourceManager.GetString("ChppScope_ManageYouthPlayers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage youth players.
        /// </summary>
        public static string ChppScope_ManageYouthPlayers_Title {
            get {
                return ResourceManager.GetString("ChppScope_ManageYouthPlayers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is allowed to place a bid on a player for sale in the name of any of your teams and remove hotlisted players..
        /// </summary>
        public static string ChppScope_PlaceBid_Description {
            get {
                return ResourceManager.GetString("ChppScope_PlaceBid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place bid.
        /// </summary>
        public static string ChppScope_PlaceBid_Title {
            get {
                return ResourceManager.GetString("ChppScope_PlaceBid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is allowed to set match orders for your coming matches..
        /// </summary>
        public static string ChppScope_SetMatchOrder_Description {
            get {
                return ResourceManager.GetString("ChppScope_SetMatchOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set match orders.
        /// </summary>
        public static string ChppScope_SetMatchOrder_Title {
            get {
                return ResourceManager.GetString("ChppScope_SetMatchOrder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is allowed to set training for any of your teams. This includes the type, percentage, and stamina share..
        /// </summary>
        public static string ChppScope_SetTraining_Description {
            get {
                return ResourceManager.GetString("ChppScope_SetTraining_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set training.
        /// </summary>
        public static string ChppScope_SetTraining_Title {
            get {
                return ResourceManager.GetString("ChppScope_SetTraining_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Authorization.
        /// </summary>
        public static string ConfirmAuthorization {
            get {
                return ResourceManager.GetString("ConfirmAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Link.
        /// </summary>
        public static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Link.
        /// </summary>
        public static string OpenLink {
            get {
                return ResourceManager.GetString("OpenLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Features.
        /// </summary>
        public static string OptionalFeatures {
            get {
                return ResourceManager.GetString("OptionalFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste verifier code returned by Hattrick in the box below..
        /// </summary>
        public static string PasteVerifier {
            get {
                return ResourceManager.GetString("PasteVerifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Supporter.
        /// </summary>
        public static string RequiresSupporter {
            get {
                return ResourceManager.GetString("RequiresSupporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifier code.
        /// </summary>
        public static string VerifierCode {
            get {
                return ResourceManager.GetString("VerifierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
