// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Mesa.HUM.Infrastructure.Persistence.Migrations
{
    [ExcludeFromCodeCoverage]
    /// <inheritdoc />
    public partial class _01_UserProfile : Migration
    {
        /// <inheritdoc />
        protected override void Up ( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.CreateTable (
                name: "user_profiles" ,
                columns: table => new
                {
                    id = table.Column<Guid> ( type: "TEXT" , fixedLength: true , nullable: false ) ,
                    chpp_token_token = table.Column<string> ( type: "TEXT" , fixedLength: true , nullable: true ) ,
                    chpp_token_token_secret = table.Column<string> ( type: "TEXT" , fixedLength: true , nullable: true ) ,
                    chpp_token_obtained_at = table.Column<DateTimeOffset> ( type: "TEXT" , fixedLength: true , nullable: true ) ,
                    chpp_token_expires_at = table.Column<DateTimeOffset> ( type: "TEXT" , fixedLength: true , nullable: true ) ,
                    synchronized_at = table.Column<DateTimeOffset> ( type: "TEXT" , fixedLength: true , nullable: true )
                } ,
                constraints: table =>
                {
                    table.PrimaryKey ( "pk_user_profiles" , x => x.id );
                } );
        }

        /// <inheritdoc />
        protected override void Down ( MigrationBuilder migrationBuilder )
        {
            migrationBuilder.DropTable (
                name: "user_profiles" );
        }
    }
}
