// <auto-generated />
using System;
using Mesa.HUM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mesa.HUM.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824170537_01_UserProfile")]
    partial class _01_UserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Mesa.HUM.Domain.Profiles.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("SynchronizedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("synchronized_at")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Mesa.HUM.Domain.Profiles.UserProfile", b =>
                {
                    b.OwnsOne("Mesa.HUM.Domain.Profiles.ValueObjects.ChppToken", "ChppToken", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("ExpiresAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("chpp_token_expires_at")
                                .IsFixedLength();

                            b1.Property<DateTimeOffset>("ObtainedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("chpp_token_obtained_at")
                                .IsFixedLength();

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("chpp_token_token")
                                .IsFixedLength();

                            b1.Property<string>("TokenSecret")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("chpp_token_token_secret")
                                .IsFixedLength();

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId")
                                .HasConstraintName("fk_user_profiles_user_profiles_id");
                        });

                    b.Navigation("ChppToken");
                });
#pragma warning restore 612, 618
        }
    }
}
