<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />

    </ItemGroup>

    <ItemGroup>
      <AvaloniaXaml Remove="Models\**" />
      <Compile Remove="Models\**" />
      <EmbeddedResource Remove="Models\**" />
      <None Remove="Models\**" />
    </ItemGroup>

    <ItemGroup>

        <PackageReference Include="Avalonia" Version="12.1.1" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />

    </ItemGroup>

    <ItemGroup>

        <ProjectReference Include="..\Mesa.HUM.Infrastructure\Mesa.HUM.Infrastructure.csproj" />
        <ProjectReference Include="..\Mesa.HUM.Presentation\Mesa.HUM.Presentation.csproj" />

    </ItemGroup>

    <ItemGroup>

        <InternalsVisibleTo Include="Mesa.HUM.UI.Desktop.Tests" />

    </ItemGroup>

    <ItemGroup>
      <None Update="appSettings.development.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="appSettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
